//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace design_forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("design_forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string EmulatorListLvcDeveloper {
            get {
                return ResourceManager.GetString("EmulatorListLvcDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EmulatorListLvcName {
            get {
                return ResourceManager.GetString("EmulatorListLvcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string EmulatorListLvcPlatform {
            get {
                return ResourceManager.GetString("EmulatorListLvcPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string EmulatorListLvcVersion {
            get {
                return ResourceManager.GetString("EmulatorListLvcVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmulatorList.
        /// </summary>
        internal static string EmulatorListName {
            get {
                return ResourceManager.GetString("EmulatorListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string EmulatorListRun {
            get {
                return ResourceManager.GetString("EmulatorListRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string FavouritesListViewPlatform {
            get {
                return ResourceManager.GetString("FavouritesListViewPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string FavouritesName {
            get {
                return ResourceManager.GetString("FavouritesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Run.
        /// </summary>
        internal static string FavouritesPlayRun {
            get {
                return ResourceManager.GetString("FavouritesPlayRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FavoutritesListViewName {
            get {
                return ResourceManager.GetString("FavoutritesListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Menu.
        /// </summary>
        internal static string GenBackToMenu {
            get {
                return ResourceManager.GetString("GenBackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator.
        /// </summary>
        internal static string GenEmulator {
            get {
                return ResourceManager.GetString("GenEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string GenGame {
            get {
                return ResourceManager.GetString("GenGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        internal static string HelpBugReport {
            get {
                return ResourceManager.GetString("HelpBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit forum.
        /// </summary>
        internal static string HelpForum {
            get {
                return ResourceManager.GetString("HelpForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpName {
            get {
                return ResourceManager.GetString("HelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ListAdd {
            get {
                return ResourceManager.GetString("ListAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favourites.
        /// </summary>
        internal static string ListAddFavourite {
            get {
                return ResourceManager.GetString("ListAddFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ListEdit {
            get {
                return ResourceManager.GetString("ListEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ListRemove {
            get {
                return ResourceManager.GetString("ListRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainHelp {
            get {
                return ResourceManager.GetString("MainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MainSearch {
            get {
                return ResourceManager.GetString("MainSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string SearchEdit {
            get {
                return ResourceManager.GetString("SearchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchName {
            get {
                return ResourceManager.GetString("SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/ Run.
        /// </summary>
        internal static string SearchPlayRun {
            get {
                return ResourceManager.GetString("SearchPlayRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SearchViewName {
            get {
                return ResourceManager.GetString("SearchViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string SearchViewPlatform {
            get {
                return ResourceManager.GetString("SearchViewPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string SettingsHeaderUI {
            get {
                return ResourceManager.GetString("SettingsHeaderUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Preset.
        /// </summary>
        internal static string SettingsLoadPreset {
            get {
                return ResourceManager.GetString("SettingsLoadPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsName {
            get {
                return ResourceManager.GetString("SettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Colour.
        /// </summary>
        internal static string SettingsOptionBGColor {
            get {
                return ResourceManager.GetString("SettingsOptionBGColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsOptionLanguage {
            get {
                return ResourceManager.GetString("SettingsOptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string SettingsOptionsFont {
            get {
                return ResourceManager.GetString("SettingsOptionsFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string SettingsOptionsScale {
            get {
                return ResourceManager.GetString("SettingsOptionsScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big.
        /// </summary>
        internal static string SettingsScaleBig {
            get {
                return ResourceManager.GetString("SettingsScaleBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Big.
        /// </summary>
        internal static string SettingsScaleExtraBig {
            get {
                return ResourceManager.GetString("SettingsScaleExtraBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string SettingsScaleMedium {
            get {
                return ResourceManager.GetString("SettingsScaleMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string SettingsScaleSmall {
            get {
                return ResourceManager.GetString("SettingsScaleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string textAbout {
            get {
                return ResourceManager.GetString("textAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Emulator.
        /// </summary>
        internal static string textAddEmulator {
            get {
                return ResourceManager.GetString("textAddEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        internal static string textAddGame {
            get {
                return ResourceManager.GetString("textAddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofill Meta-Data.
        /// </summary>
        internal static string textAutofillMetadata {
            get {
                return ResourceManager.GetString("textAutofillMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Report.
        /// </summary>
        internal static string textBugReport {
            get {
                return ResourceManager.GetString("textBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string textCancel {
            get {
                return ResourceManager.GetString("textCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string textColor {
            get {
                return ResourceManager.GetString("textColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string textDeveloper {
            get {
                return ResourceManager.GetString("textDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string textEdit {
            get {
                return ResourceManager.GetString("textEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Emulator.
        /// </summary>
        internal static string textEditEmulator {
            get {
                return ResourceManager.GetString("textEditEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Game.
        /// </summary>
        internal static string textEditGame {
            get {
                return ResourceManager.GetString("textEditGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator.
        /// </summary>
        internal static string textEmulator {
            get {
                return ResourceManager.GetString("textEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string textFavourites {
            get {
                return ResourceManager.GetString("textFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string textFont {
            get {
                return ResourceManager.GetString("textFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string textForum {
            get {
                return ResourceManager.GetString("textForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string textGame {
            get {
                return ResourceManager.GetString("textGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string textGeneral {
            get {
                return ResourceManager.GetString("textGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string textHelp {
            get {
                return ResourceManager.GetString("textHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string textLanguage {
            get {
                return ResourceManager.GetString("textLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Preset.
        /// </summary>
        internal static string textLoadPreset {
            get {
                return ResourceManager.GetString("textLoadPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string textLocation {
            get {
                return ResourceManager.GetString("textLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string textName {
            get {
                return ResourceManager.GetString("textName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string textOk {
            get {
                return ResourceManager.GetString("textOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string textPlatform {
            get {
                return ResourceManager.GetString("textPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string textPlay {
            get {
                return ResourceManager.GetString("textPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string textScale {
            get {
                return ResourceManager.GetString("textScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string textSearch {
            get {
                return ResourceManager.GetString("textSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string textSettings {
            get {
                return ResourceManager.GetString("textSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string textTitle {
            get {
                return ResourceManager.GetString("textTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unilator.
        /// </summary>
        internal static string textUnilator {
            get {
                return ResourceManager.GetString("textUnilator", resourceCulture);
            }
        }
    }
}
