//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace design_forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("design_forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01a5dcde8a3c9b424e105185677ed8d6_plus {
            get {
                object obj = ResourceManager.GetObject("01a5dcde8a3c9b424e105185677ed8d6-plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _340 {
            get {
                object obj = ResourceManager.GetObject("340", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap controller {
            get {
                object obj = ResourceManager.GetObject("controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emulator {
            get {
                object obj = ResourceManager.GetObject("emulator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Heart {
            get {
                object obj = ResourceManager.GetObject("Heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Heart1 {
            get {
                object obj = ResourceManager.GetObject("Heart1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Heart2 {
            get {
                object obj = ResourceManager.GetObject("Heart2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imageedit_1_4773648694 {
            get {
                object obj = ResourceManager.GetObject("imageedit_1_4773648694", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionmark {
            get {
                object obj = ResourceManager.GetObject("questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Redo1 {
            get {
                object obj = ResourceManager.GetObject("Redo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove1 {
            get {
                object obj = ResourceManager.GetObject("remove1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string textAbout {
            get {
                return ResourceManager.GetString("textAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string textAdd {
            get {
                return ResourceManager.GetString("textAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to favourites.
        /// </summary>
        internal static string textAddedToFavourites {
            get {
                return ResourceManager.GetString("textAddedToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Emulator.
        /// </summary>
        internal static string textAddEmulator {
            get {
                return ResourceManager.GetString("textAddEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        internal static string textAddGame {
            get {
                return ResourceManager.GetString("textAddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favourites.
        /// </summary>
        internal static string textAddToFavourites {
            get {
                return ResourceManager.GetString("textAddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofill Meta-Data.
        /// </summary>
        internal static string textAutofillMetadata {
            get {
                return ResourceManager.GetString("textAutofillMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Report.
        /// </summary>
        internal static string textBugReport {
            get {
                return ResourceManager.GetString("textBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string textCancel {
            get {
                return ResourceManager.GetString("textCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string textColor {
            get {
                return ResourceManager.GetString("textColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string textConfirmation {
            get {
                return ResourceManager.GetString("textConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string textDeveloper {
            get {
                return ResourceManager.GetString("textDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing game &apos;{0}&apos;.
        /// </summary>
        internal static string textDummyPlay {
            get {
                return ResourceManager.GetString("textDummyPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string textEdit {
            get {
                return ResourceManager.GetString("textEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Emulator.
        /// </summary>
        internal static string textEditEmulator {
            get {
                return ResourceManager.GetString("textEditEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Game.
        /// </summary>
        internal static string textEditGame {
            get {
                return ResourceManager.GetString("textEditGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator.
        /// </summary>
        internal static string textEmulator {
            get {
                return ResourceManager.GetString("textEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This emulator is already added.
        /// </summary>
        internal static string textEmulatorAlreadyAdded {
            get {
                return ResourceManager.GetString("textEmulatorAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulators.
        /// </summary>
        internal static string textEmulators {
            get {
                return ResourceManager.GetString("textEmulators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string textFavourites {
            get {
                return ResourceManager.GetString("textFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string textFont {
            get {
                return ResourceManager.GetString("textFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string textForum {
            get {
                return ResourceManager.GetString("textForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string textGame {
            get {
                return ResourceManager.GetString("textGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is already added.
        /// </summary>
        internal static string textGameAlreadyAdded {
            get {
                return ResourceManager.GetString("textGameAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string textGames {
            get {
                return ResourceManager.GetString("textGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string textGeneral {
            get {
                return ResourceManager.GetString("textGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string textHelp {
            get {
                return ResourceManager.GetString("textHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given emulator developer is invalid.
        /// </summary>
        internal static string textInvalidEmulatorDeveloper {
            get {
                return ResourceManager.GetString("textInvalidEmulatorDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given emulator location is invalid.
        /// </summary>
        internal static string textInvalidEmulatorLocation {
            get {
                return ResourceManager.GetString("textInvalidEmulatorLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given emulator name is invalid.
        /// </summary>
        internal static string textInvalidEmulatorName {
            get {
                return ResourceManager.GetString("textInvalidEmulatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given emulator platform is invalid.
        /// </summary>
        internal static string textInvalidEmulatorPlatform {
            get {
                return ResourceManager.GetString("textInvalidEmulatorPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given game emulator is invalid.
        /// </summary>
        internal static string textInvalidGameEmulator {
            get {
                return ResourceManager.GetString("textInvalidGameEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given game location is invalid.
        /// </summary>
        internal static string textInvalidGameLocation {
            get {
                return ResourceManager.GetString("textInvalidGameLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given game name is invalid.
        /// </summary>
        internal static string textInvalidGameName {
            get {
                return ResourceManager.GetString("textInvalidGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string textInvalidInput {
            get {
                return ResourceManager.GetString("textInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string textLanguage {
            get {
                return ResourceManager.GetString("textLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Preset.
        /// </summary>
        internal static string textLoadPreset {
            get {
                return ResourceManager.GetString("textLoadPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string textLocation {
            get {
                return ResourceManager.GetString("textLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string textName {
            get {
                return ResourceManager.GetString("textName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string textOk {
            get {
                return ResourceManager.GetString("textOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string textPlatform {
            get {
                return ResourceManager.GetString("textPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string textPlay {
            get {
                return ResourceManager.GetString("textPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string textRemove {
            get {
                return ResourceManager.GetString("textRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string textScale {
            get {
                return ResourceManager.GetString("textScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string textSearch {
            get {
                return ResourceManager.GetString("textSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string textSettings {
            get {
                return ResourceManager.GetString("textSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string textTitle {
            get {
                return ResourceManager.GetString("textTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unilator.
        /// </summary>
        internal static string textUnilator {
            get {
                return ResourceManager.GetString("textUnilator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Undo1 {
            get {
                object obj = ResourceManager.GetObject("Undo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
